#!/bin/bash

GREEN="\033[1;32m"
RED="\033[1;31m"
BLUE="\033[1;34m"
YELLOW="\033[1;33m"
ENDCOLOR="\033[0m"

echo -e "${BLUE}[BEGIN]${ENDCOLOR} Beginning Picto development build process."
echo

echo -e "${BLUE}[CHECK]${ENDCOLOR} ./app/config/build.settings exists."
if [ ! -f ./app/config/build.settings ]
then
    echo -e "${RED}[FAILURE]${ENDCOLOR} The ./app/config/build.settings file does not exist. Create it from ./app/config/build.settings.template."
    exit 1
fi
echo -e "${GREEN}[OK]${ENDCOLOR} ./app/config/build.settings exists."
echo

echo -e "${BLUE}[INSTALL]${ENDCOLOR} Installing Composer."
curl -s https://getcomposer.org/installer | php >/dev/null 2>&1

echo -e "${BLUE}[INSTALL]${ENDCOLOR} Installing PHPUnit."
wget -qO phpunit.phar https://phar.phpunit.de/phpunit.phar -O phpunit.phar

echo -e "${BLUE}[INSTALL]${ENDCOLOR} Installing Phing."
wget -qO phing.phar http://www.phing.info/get/phing-2.6.1.phar
echo

echo -e "${BLUE}[BEGIN]${ENDCOLOR} Building the Picto project."

if [ ! -d "log" ]; then
    mkdir log
fi

php phing.phar -Dbuild_settings_file=app/config/build.settings build

echo -e "${GREEN}[FINISHED]${ENDCOLOR} Building the Picto project."

echo
echo -e "${GREEN}####################################################################${ENDCOLOR}"
echo -e "${GREEN}# [SUCCESS] The Picto project is ready to go!                      #${ENDCOLOR}"
echo -e "${GREEN}####################################################################${ENDCOLOR}"
echo

exit 0
